FROM node:18-alpine As build
WORKDIR /usr/src/app
COPY --chown=node:node package*.json ./
COPY --chown=node:node prisma ./prisma
COPY --chown=node:node . .
RUN npm ci
RUN npm run build
USER node

FROM node:18-alpine As production
COPY --chown=node:node --from=build /usr/src/app/ ./
COPY --chown=node:node --from=build /usr/src/app/dist ./dist
COPY --chown=node:node --from=build /usr/src/app/prisma ./prisma
COPY --chown=node:node --from=build /usr/src/app/node_modules ./node_modules
CMD [ "npm", "run", "start:prod" ]